### ISSUE TITLE
Implement new routing API

### ISSUE THREAD

**Issue by JasonDalton** [Azimuth1/ruralwater#5]
Cloudmade dropped their geocoding and routing APIs.   This one looks like a good replacement:  http://developer.mapquest.com/web/products/open/directions-service

**Comment by skitol** [comment]
Have you seen this? 

https://github.com/perliedman/leaflet-routing-machine
http://www.liedman.net/leaflet-routing-machine/

**Comment by JasonDalton** [comment]
The Leaflet routing machine seems to work great.   Very speedy even though it's using the hosted demo of OSM routing machine.

**Comment by JasonDalton** [comment]
@skitol  If I fork the Leaflet routing machine can I reference it in my JS in Github Pages?

**Comment by skitol** [comment]
@JasonDalton  were you thinking of just using the Nominatim API from the demo? If so - prob not a good idea in production, with their terms of service. 

Regardless, I guess you technically could - but it's a hack:

http://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github
